name: GPU (single node)
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: namo626/setup-fortran@main
        id: setup-fortran
        with:
          compiler: nvidia-hpc
          version: '24.5'


      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Python packages
        run: pip install -r requirements.txt

      - name: Compile
        run: make gpu=1 dgswem_serial
        working-directory: work

      - name: Testcases
        id: testcases
        run: make test
        working-directory: work
