name: Compilation and test cases
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        toolchain:
          - {compiler: gcc, version: 12}
          - {compiler: gcc, version: 13}
          - {compiler: nvidia-hpc, version: '24.5'}
          - {compiler: nvidia-hpc, version: '25.1'}

    steps:
      - uses: namo626/setup-fortran@main
        id: setup-fortran
        with:
          compiler: ${{ matrix.toolchain.compiler }}
          version: ${{ matrix.toolchain.version }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Python packages
        run: pip install -r requirements.txt

      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile
        run: make
        working-directory: work

      - name: Testcases
        run: make test
        working-directory: work
