on: [pull_request, workflow_dispatch]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        toolchain:
          - {compiler: gcc, version: 12}
          - {compiler: gcc, version: 13}
          - {compiler: nvidia-hpc, version: '23.3'}
          - {compiler: nvidia-hpc, version: '24.5'}
          - {compiler: nvidia-hpc, version: '25.1'}

    steps:
      - uses: namo626/setup-fortran
        id: setup-fortran
        with:
          compiler: ${{ matrix.toolchain.compiler }}
          version: ${{ matrix.toolchain.version }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile
        run: make
        working-directory: work

      # - name: Test
      # - run: make test
